namespace :location do

  desc 'Update Locations meta data'
  task update_metadata: :environment do
    puts "####### Starting updating metadata ######"
    franchiseLocations = FranchiseLocation.find(:all)
    franchiseLocations.each do |location|
      case location.address.strip
        when "1 Toronto Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 1 Toronto Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "3 Rees Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 3 Rees Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "707 Yonge Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 707 Yonge Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "270 Adelaide Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 270 Adelaide Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "624 Queen Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 624 Queen Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "615 King Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 615 King Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "722 Queen Street E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 722 Queen Street E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "104 Yonge Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 104 Yonge Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "289 Dundas Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 289 Dundas Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "346 Bloor Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 346 Bloor Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "1528 Danforth Ave"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 1528 Danforth Ave"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"  
        when "953 Eglinton Ave W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 953 Eglinton Ave W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "13 St. Clair Av"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 13 St. Clair Av"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "3369 Yonge Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 3369 Yonge Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"  
        when "745 Mount Pleasant"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 745 Mount Pleasant"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "865 York Mills Rd"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 865 York Mills Rd"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "4920 Yonge Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 4920 Yonge Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "2425 Bloor Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 2425 Bloor Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "3339 Bloor Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 3339 Bloor Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "56 Lakeshore Rd E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 56 Lakeshore Rd E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "37 Eglinton Ave E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 37 Eglinton Ave E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "123 Spadina Ave"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 123 Spadina Ave"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"  
        when "341 Lakeshore Rd E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 341 Lakeshore Rd E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "3180 Lakeshore Blvd W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 3180 Lakeshore Blvd W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "1172 Queen Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 1172 Queen Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "3480 Fairview Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 3480 Fairview Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "383 Roncesvalles Ave"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 383 Roncesvalles Ave"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "130 Guelph Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 130 Guelph Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "115 York Blvd"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 115 York Blvd"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "110 Danforth Ave"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 110 Danforth Ave"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "5130 Dixie Rd"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 5130 Dixie Rd"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "182 Main Street E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 182 Main Street E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "1477 Lakeshore Rd"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 1477 Lakeshore Rd"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "1160 St. Clair Ave W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 1160 St. Clair Ave W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "10211 Keele Street"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 10211 Keele Street"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
        when "229 Queen Street S"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 229 Queen Street S"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########"
         when "2335 Trafalgar Rd"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 2335 Trafalgar Rd"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "2253 Queen Street E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 2253 Queen Street E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "416 Bloor Street W"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 416 Bloor Street W"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
        when "366 Bloor Street E"
          puts "####### Starting updating metadata for location: #{location.address.strip} ########"
          location.seo_title = "Pizzaiolo | Gourmet Pizza | Locations | #{location.area_name} | 366 Bloor Street E"
          location.seo_metadescription = "Check out Pizzaiolo's menu of gourmet pizzas made with fresh, never frozen ingredients. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!"
          location.seo_keywords = "Pizzaiolo, Local Pizza, Delivery, Order Online Takeout, Gluten Free, Vegan, Gourmet Pizza,"
          puts "####### Ending updating metadata for location: #{location.address.strip} ########" 
      end
      location.save
    end
    puts "####### Ending updating metadata ######"
  end

end