# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout

      - type: shell
        name: Install System dependencies
        command: sudo apt-get update -qq && sudo apt-get install -y build-essential libsasl2-dev postgresql-contrib

      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: 'Build & Push Docker Image'
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ] || [ "${CIRCLE_BRANCH}" == "staging" ] || [ "${CIRCLE_BRANCH}" == "delivery-timing2" ] || [ "${CIRCLE_BRANCH}" == "pepperoni_special" ] || [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "staging3" ]; then
              TAG=$CIRCLE_BUILD_NUM
              docker build -t pizzaiolodocker/dev:$TAG .
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push pizzaiolodocker/dev:$TAG
            fi
