FRANCHISE_LOCATION_CLOSING_OFFSET = 45.minutes

FRANCHISE_LOCATION_PICKUP_OFFSET = 25.minutes
FRANCHISE_LOCATION_DELIVERY_OFFSET = 40.minutes

FRANCHISE_LOCATION_PICKUP_PREP_TIME = 25.minutes
FRANCHISE_LOCATION_DELIVERY_PREP_TIME = 40.minutes

DATE_FORMAT = "%B %d, %Y %I:%M%P"
DATE_ONLY_FORMAT = "%B %d, %Y"
TIME_ONLY_FORMAT = "%I:%M %P"
